/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Leo' at '8/28/15 3:11 AM' with Gradle 2.6
 *
 * @author Leo, @date 8/28/15 3:11 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
