/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Leo' at '9/2/15 4:58 AM' with Gradle 2.6
 *
 * @author Leo, @date 9/2/15 4:58 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
